name: CI/CD Pipeline for Client application

on:
  push:
    branches:
      - main
    paths:
      - 'apps/client'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  VITE_API_URL: ${{ secrets.VITE_API_URL}}
  VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
  VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID}}
  VITE_AUTH0_CALLBACK_URL: ${{ secrets.VITE_AUTH0_CALLBACK_URL }}
  VITE_API_AUTH0_AUDIENCE: ${{ secrets.VITE_API_AUTH0_AUDIENCE}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/client

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

      - name: Build React App
        run: npm install
        
      - name: Install Dependencies
        run: npm run build

      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./dist/ s3://x22212973-inventory-app-production --delete
