name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

env:
  TF_WORKSPACE: production
  TF_VAR_doppler_token: ${{ secrets.TF_VAR_DOPPLER_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  infrastructure:
    name: Terraform infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.5'

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
