name: CI/CD Pipeline for backend application

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api'

env:
  EB_ARTIFACTS_BUCKET: '${{ secrets.PROJECT_NAME }}/eb-artifacts'
  EB_APPLICATION_NAME: ${{ secrets.PROJECT_NAME }}
  EB_ENVIRONMENT_NAME: '${{ secrets.PROJECT_NAME }}-production'
  APP_BUNDLE_NAME: '${{ secrets.PROJECT_NAME }}-${{ github.sha }}.zip'
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Create zip deployment package
        run: zip -r ${{ env.APP_BUNDLE_NAME }} ./ -x ./.git -x *.git

      - name: Upload package to S3 bucket
        run: aws s3 cp ${{ env.APP_BUNDLE_NAME }} s3://${{env.EB_ARTIFACTS_BUCKET}}

  deploy:
    name: Deploy artifacts
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{env.EB_APPLICATION_NAME}} \
          --version-label "${{ github.sha }}" \
          --source-bundle S3Bucket="${{ env.EB_ARTIFACTS_BUCKET }}",S3Key="${{ env.APP_BUNDLE_NAME }}"

      - name: Deploy new application version
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
          --version-label "${{ github.sha }}"
